# This is a basic workflow to help you get started with Actions
 
name:
  Newsletter Cron Job
 
  # Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Triggers the workflow every 5 minutes
  schedule:
    - cron: "0 8 * * *"
 
      # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# Default to bash
defaults:
  run:
    shell: bash
    

jobs:
  # Build job
  geenrate:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.114.0
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Install Dart Sass
        run: sudo snap install dart-sass
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Install Node.js dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
      - name: setup go env
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          check-latest: true
      - name: generate page
        run: hugo new -k page newsletter/$(date +"%Y-%m-%d").md
      - name: clone lib
        run: git clone https://github.com/yifu-yang/HackerNewsBot.git ../HackerNewsBot
      - name: get HN content
        run: go run main.go content/newsletter/$(date +"%Y-%m-%d").md
      - name: commit newsletter
        uses: EndBug/add-and-commit@v9
        with:
          author_name: yifu-yang
          author_email: 576843117@qq.com
          message: $(date +"%Y-%m-%d")
          add: '*'

